package com.pdflibya.app;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Bitmap;import android.graphics.BitmapFactory;import android.net.Uri;import android.webkit.*;import android.widget.Toast;import java.io.*;import java.util.*;
import com.tom_roush.pdfbox.pdmodel.*;import com.tom_roush.pdfbox.pdmodel.common.PDRectangle;import com.tom_roush.pdfbox.multipdf.PDFMergerUtility;import com.tom_roush.pdfbox.pdmodel.graphics.image.LosslessFactory;

public class MainActivity extends Activity{
 WebView web; static final int PICK=1001,PICK_MULTI=1002; String action="";
 public void onCreate(Bundle b){super.onCreate(b);web=new WebView(this);WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);web.setWebViewClient(new WebViewClient());web.addJavascriptInterface(new Bridge(),"Android");web.loadUrl("file:///android_asset/index.html");setContentView(web);}
 void pick(boolean multi,String a){action=a;Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType(a.equals("image")?"image/*":"application/pdf");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,multi);i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,multi?PICK_MULTI:PICK);}
 protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK||d==null)return;ArrayList<Uri> u=new ArrayList<>();if(d.getClipData()!=null){for(int n=0;n<d.getClipData().getItemCount();n++)u.add(d.getClipData().getItemAt(n).getUri());}else if(d.getData()!=null)u.add(d.getData());try{File f=null;if(action.equals("image"))f=imagesToPdf(u);else if(action.equals("merge"))f=merge(u);else if(action.equals("split"))f=split(u.get(0));else if(action.equals("compress"))f=compress(u.get(0));if(f!=null){share(f);web.evaluateJavascript("window.done('"+f.getName().replace("'"," ")+"')",null);}}catch(Exception e){Toast.makeText(this,"حدث خطأ: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
 File dir(){File d=new File(getExternalFilesDir(null),"PDFLibya");d.mkdirs();return d;}
 File imagesToPdf(ArrayList<Uri> us)throws Exception{PDDocument d=new PDDocument();for(Uri x:us){InputStream in=getContentResolver().openInputStream(x);Bitmap b=BitmapFactory.decodeStream(in);in.close();if(b==null)continue;float w=595,h=w*b.getHeight()/Math.max(1f,b.getWidth());PDPage p=new PDPage(new PDRectangle(w,h));d.addPage(p);org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject im=LosslessFactory.createFromImage(d,b);PDPageContentStream cs=new PDPageContentStream(d,p);cs.drawImage(im,0,0,w,h);cs.close();b.recycle();}File f=new File(dir(),"PDF_Libya_"+System.currentTimeMillis()+".pdf");d.save(f);d.close();return f;}
 File merge(ArrayList<Uri> us)throws Exception{PDFMergerUtility m=new PDFMergerUtility();File f=new File(dir(),"PDF_Libya_Merged_"+System.currentTimeMillis()+".pdf");m.setDestinationFileName(f.getAbsolutePath());for(Uri x:us)m.addSource(getContentResolver().openInputStream(x));m.mergeDocuments(null);return f;}
 File split(Uri u)throws Exception{PDDocument s=PDDocument.load(getContentResolver().openInputStream(u));File f=new File(dir(),"PDF_Libya_Split_"+System.currentTimeMillis()+".pdf");PDDocument o=new PDDocument();if(s.getNumberOfPages()>0)o.importPage(s.getPage(0));o.save(f);o.close();s.close();return f;}
 File compress(Uri u)throws Exception{PDDocument d=PDDocument.load(getContentResolver().openInputStream(u));File f=new File(dir(),"PDF_Libya_Compressed_"+System.currentTimeMillis()+".pdf");d.save(f);d.close();return f;}
 void share(File f){Intent i=new Intent(Intent.ACTION_SEND);i.setType("application/pdf");i.putExtra(Intent.EXTRA_STREAM,androidx.core.content.FileProvider.getUriForFile(this,getPackageName()+".provider",f));i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,"مشاركة ملف PDF"));}
 public class Bridge{@JavascriptInterface public void pickImage(){pick(true,"image");}@JavascriptInterface public void merge(){pick(true,"merge");}@JavascriptInterface public void split(){pick(false,"split");}@JavascriptInterface public void compress(){pick(false,"compress");}}
}